name: TESTAR (02_webdriver_parabank)

on:
  push:
    branches: [ protocol-self-hosted ]

jobs:
  testar-web:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Run TESTAR
        shell: pwsh
        run: |
          $testarPath = "C:\testar\bin"
          Set-Location $testarPath
          .\testar.bat `
            sse=02_webdriver_parabank `
            WebDomainsAllowed=null `
            WebPathsAllowed=null `
            ShowVisualSettingsDialogOnStartup=false `
            FlashFeedback=false `
            AlwaysCompile=true `
            Mode=Generate `
            ApplicationName='"parabank_ci"' `
            SUTConnectorValue='" ""C:\\SeleniumWebDrivers\\ChromeDriver\\chromedriver.exe"" ""https://para.testar.org/"" "' `
            Sequences=3 `
            SequenceLength=5 `
            SuspiciousTitles='"Invalid"'

      - name: Upload TESTAR output results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: testar-output-results
          path: testar/bin/output
