name: Test TESTAR Action (webdriver_generic)

on:
  push:
    branches: [ web-self-hosted ]
  workflow_dispatch:

jobs:
  testar-web:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Run TESTAR Action (webdriver_generic)
        uses: ferpasri/TESTAR_Action@main
        with:
          application_name: 'parabank'
          sut: 'https://para.testar.org/parabank/'
          sequences: '3'
          sequence_length: '5'
          suspicious_titles: '.[eE]rror.|.[eE]xcep[ct]ion.|.[iI]nvalid.'
